### ISSUE TITLE
Subject, Event and CRF attributes

### ISSUE THREAD

**Issue by K-V-N** [lindsay-stevens/openclinica_scripts#3]
I noticed that not all subject, event and CRF attributes are converted to the R files. I'm not familiar enough with XLS to edit the files myself. In particular, I would like Subject Sex, Event Start date and Event Subject age at event in my R data frames. 

Could someone guide me how to edit the XLS accordingly?

The data points I need, like Subject Sex, are available in the ODM XML:

```
<ClinicalData StudyOID="REDACTED" MetaDataVersionOID="v1.0.0-REDACTED">
<SubjectData SubjectKey="SS_1001" OpenClinica:StudySubjectID="1001" OpenClinica:Sex="f">
```

**Comment by lindsay-stevens** [comment]
Thanks for contribution, PR #4 is complete. I added a test file from the OpenClinica demo database, and made a minor change to your code so that the event start date and subject age at event data are output properly.
